## Final Project Submission

Please fill out:
* Student name: Linh Mai
* Student pace: self paced 
* Scheduled project review date/time: June 3rd, 2020
* Instructor name: Jeff Herman
* Blog post URL: https://linhmai19.github.io/

In [1]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
%matplotlib inline 
plt.style.use('seaborn')

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.api as sms
import scipy.stats as stats

In [2]:
df = pd.read_csv('cleaned_kc_house_data.csv')
df = df.drop('Unnamed: 0', 1)
df.head()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,...,yr_sold,zip_98008_98028,zip_98028_98038,zip_98038_98053,zip_98053_98065,zip_98065_98103,zip_98103_98115,zip_98115_98125,zip_98125_98155,zip_98155_98200
0,221900.0,0.333333,0.090909,0.369910,0.661603,0.000000,0.0,0.0,0.333333,0.333333,...,2014,0,0,0,0,0,0,0,0,1
1,538000.0,0.333333,0.545455,0.756227,0.730449,0.553295,0.0,0.0,0.333333,0.333333,...,2014,0,0,0,0,0,0,1,0,0
2,180000.0,0.000000,0.090909,0.158049,0.819942,0.000000,0.0,0.0,0.333333,0.000000,...,2015,1,0,0,0,0,0,0,0,0
3,604000.0,0.666667,0.818182,0.621749,0.627708,0.000000,0.0,0.0,1.000000,0.333333,...,2014,0,0,0,0,0,0,0,1,0
4,510000.0,0.333333,0.454545,0.545243,0.760816,0.000000,0.0,0.0,0.333333,0.666667,...,2015,0,0,0,0,1,0,0,0,0

## Running Linear Regression

In [4]:
outcome = 'price'
predictors = df.drop(['price'], axis=1)
pred_sum = '+'.join(predictors.columns)
formula = outcome + '~' + pred_sum

model = ols(formula=formula, data=df).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.573
Model:                            OLS   Adj. R-squared:                  0.572
Method:                 Least Squares   F-statistic:                     1011.
Date:                Fri, 29 May 2020   Prob (F-statistic):               0.00
Time:                        11:15:50   Log-Likelihood:            -2.1852e+05
No. Observations:               16614   AIC:                         4.371e+05
Df Residuals:                   16591   BIC:                         4.373e+05
Df Model:                          22
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
Intercept        -2.92e+07   4.19e+06     -6.976      0.000   -3.74e+07    -2.1e+07
bedrooms        -3.612e+04   4947.484     -7.300      0.000   -4.58e+04   -2.64e+04
bathrooms        4.395e+04   7043.053      6.240      0.000    3.01e+04    5.78e+04
sqft_living      3.009e+05   1.18e+04     25.599      0.000    2.78e+05    3.24e+05
sqft_lot         -1.42e+05   8972.059    -15.829      0.000    -1.6e+05   -1.24e+05
floors           1.837e+04   5826.434      3.153      0.002    6949.802    2.98e+04
waterfront       1.946e+05   3.11e+04      6.253      0.000    1.34e+05    2.56e+05
view             1.136e+05   7313.150     15.537      0.000    9.93e+04    1.28e+05
condition        7.207e+04   5025.441     14.340      0.000    6.22e+04    8.19e+04
grade            2.701e+05   5394.141     50.065      0.000    2.59e+05    2.81e+05
basement         6676.0728   2618.958      2.549      0.011    1542.635    1.18e+04
yr_built        -2249.6640     51.222    -43.919      0.000   -2350.066   -2149.262
sqft_living15    2.307e+05   9489.168     24.307      0.000    2.12e+05    2.49e+05
yr_sold          1.674e+04   2077.584      8.056      0.000    1.27e+04    2.08e+04
zip_98008_98028 -7.472e+04   4581.957    -16.307      0.000   -8.37e+04   -6.57e+04
zip_98028_98038 -3.292e+04   4180.762     -7.874      0.000   -4.11e+04   -2.47e+04
zip_98038_98053  2.538e+04   4635.733      5.474      0.000    1.63e+04    3.45e+04
zip_98053_98065 -7.743e+04   4543.824    -17.040      0.000   -8.63e+04   -6.85e+04
zip_98065_98103  1.607e+04   4663.402      3.445      0.001    6925.322    2.52e+04
zip_98103_98115  4.998e+04   4862.091     10.279      0.000    4.04e+04    5.95e+04
zip_98115_98125  3.416e+04   4638.574      7.365      0.000    2.51e+04    4.33e+04
zip_98125_98155 -1.425e+04   4413.510     -3.230      0.001   -2.29e+04   -5603.626
zip_98155_98200  -5.43e+04   4664.794    -11.640      0.000   -6.34e+04   -4.52e+04
==============================================================================
Omnibus:                      632.392   Durbin-Watson:                   1.991
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              919.918
Skew:                           0.375   Prob(JB):                    1.75e-200
Kurtosis:                       3.875   Cond. No.                     1.22e+07
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.22e+07. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

### Train-Split test and calculating MSE

In [5]:
# Split the dataset into training and testing parts
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Checking the length of each data set
print(len(X_train), len(X_test), len(y_train), len(y_test))

13291 3323 13291 3323

In [6]:
# Create an instance of the model
linreg = LinearRegression()

# Fit the model
linreg.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [7]:
# Calculate predictions on training and testing datasets
y_hat_train = linreg.predict(X_train)
y_hat_test = linreg.predict(X_test)

# Calculating MSE by using Scikit-Learn's Mean Squared Error function
train_mse = mean_squared_error(y_train, y_hat_train)
test_mse = mean_squared_error(y_test, y_hat_test)
print('Train Mean Squarred Error:', train_mse)
print('Test Mean Squarred Error:', test_mse)

Train Mean Squarred Error: 15494173166.35873
Test Mean Squarred Error: 15812815642.073904

In [8]:
# Calculate the percentage of difference between the train and test MSE
print((test_mse-train_mse)/train_mse)

0.0205653100874732

The difference between train and test MSE scores is small.

## Verifying Linearity

Function for visually inspecting the assumption of linearity in a linear regression model. It plots observed vs. predicted values and residuals vs. predicted values.
    * model - fitted OLS model from statsmodels
    * y - observed values